import unittest

from bowling import BowlingGame
from bowling_error import BowlingError
from frame import Frame


class TestBowlingGame(unittest.TestCase):

    def test_game_points_sum(self):
        game = BowlingGame()
        f0 = Frame(10, 0)
        f1 = Frame(10, 0)
        f2 = Frame(10, 0)
        f3 = Frame(10, 0)
        f4 = Frame(10, 0)
        f5 = Frame(10, 0)
        f6 = Frame(10, 0)
        f7 = Frame(10, 0)
        f8 = Frame(10, 0)
        f9 = Frame(10, 0)

        game.add_frame(f0)
        game.add_frame(f1)
        game.add_frame(f2)
        game.add_frame(f3)
        game.add_frame(f4)
        game.add_frame(f5)
        game.add_frame(f6)
        game.add_frame(f7)
        game.add_frame(f8)
        game.add_frame(f9)
        game.set_first_bonus_throw(10)
        game.set_second_bonus_throw(10)

        self.assertEqual(300, game.calculate_score())

    def test_game_points_sum(self):
        game = BowlingGame()
        f0 = Frame(1, 5)
        f1 = Frame(3,6)
        f2 = Frame(7,2)
        f3 = Frame(3,6)
        f4 = Frame(4,4)
        f5 = Frame(5,3)
        f6 = Frame(3,3)
        f7 = Frame(4,5)
        f8 = Frame(8,1)
        f9 = Frame(2,8)

        game.add_frame(f0)
        game.add_frame(f1)
        game.add_frame(f2)
        game.add_frame(f3)
        game.add_frame(f4)
        game.add_frame(f5)
        game.add_frame(f6)
        game.add_frame(f7)
        game.add_frame(f8)
        game.add_frame(f9)
        game.set_first_bonus_throw(7)

        self.assertEqual(90, game.calculate_score())

    def test_game_spare_spare_frames(self):
        game = BowlingGame()
        f0 = Frame(8, 2)
        f1 = Frame(5,5)
        f2 = Frame(7,2)
        f3 = Frame(3,6)
        f4 = Frame(4,4)
        f5 = Frame(5,3)
        f6 = Frame(3,3)
        f7 = Frame(4,5)
        f8 = Frame(8,1)
        f9 = Frame(2,6)

        game.add_frame(f0)
        game.add_frame(f1)
        game.add_frame(f2)
        game.add_frame(f3)
        game.add_frame(f4)
        game.add_frame(f5)
        game.add_frame(f6)
        game.add_frame(f7)
        game.add_frame(f8)
        game.add_frame(f9)
        self.assertEqual(98, game.calculate_score())

    def test_game_strike_strike_frames(self):
        game = BowlingGame()
        f0 = Frame(10, 0)
        f1 = Frame(10,0)
        f2 = Frame(7,2)
        f3 = Frame(3,6)
        f4 = Frame(4,4)
        f5 = Frame(5,3)
        f6 = Frame(3,3)
        f7 = Frame(4,5)
        f8 = Frame(8,1)
        f9 = Frame(2,6)

        game.add_frame(f0)
        game.add_frame(f1)
        game.add_frame(f2)
        game.add_frame(f3)
        game.add_frame(f4)
        game.add_frame(f5)
        game.add_frame(f6)
        game.add_frame(f7)
        game.add_frame(f8)
        game.add_frame(f9)

        self.assertEqual(112, game.calculate_score())

    def test_game_strike_spare_frames(self):
        game = BowlingGame()
        f0 = Frame(10, 0)
        f1 = Frame(4,6)
        f2 = Frame(7,2)
        f3 = Frame(3,6)
        f4 = Frame(4,4)
        f5 = Frame(5,3)
        f6 = Frame(3,3)
        f7 = Frame(4,5)
        f8 = Frame(8,1)
        f9 = Frame(2,6)

        game.add_frame(f0)
        game.add_frame(f1)
        game.add_frame(f2)
        game.add_frame(f3)
        game.add_frame(f4)
        game.add_frame(f5)
        game.add_frame(f6)
        game.add_frame(f7)
        game.add_frame(f8)
        game.add_frame(f9)

        self.assertEqual(103, game.calculate_score())

    def test_game_strike_frames(self):
        game = BowlingGame()
        f0 = Frame(10, 0)
        f1 = Frame(3,6)
        f2 = Frame(7,2)
        f3 = Frame(3,6)
        f4 = Frame(4,4)
        f5 = Frame(5,3)
        f6 = Frame(3,3)
        f7 = Frame(4,5)
        f8 = Frame(8,1)
        f9 = Frame(2,6)

        game.add_frame(f0)
        game.add_frame(f1)
        game.add_frame(f2)
        game.add_frame(f3)
        game.add_frame(f4)
        game.add_frame(f5)
        game.add_frame(f6)
        game.add_frame(f7)
        game.add_frame(f8)
        game.add_frame(f9)

        self.assertEqual(94, game.calculate_score())

    def test_game_spare_frames(self):
        game = BowlingGame()
        f0 = Frame(1, 9)
        f1 = Frame(3,6)
        f2 = Frame(7,2)
        f3 = Frame(3,6)
        f4 = Frame(4,4)
        f5 = Frame(5,3)
        f6 = Frame(3,3)
        f7 = Frame(4,5)
        f8 = Frame(8,1)
        f9 = Frame(2,6)

        game.add_frame(f0)
        game.add_frame(f1)
        game.add_frame(f2)
        game.add_frame(f3)
        game.add_frame(f4)
        game.add_frame(f5)
        game.add_frame(f6)
        game.add_frame(f7)
        game.add_frame(f8)
        game.add_frame(f9)

        self.assertEqual(88, game.calculate_score())

    def test_game_creation(self):
        f = Frame(1,5)
        game = BowlingGame()
        game.add_frame(f)
        self.assertEqual(f, game.get_frame_at(0))

    def test_game_empty(self):
        game = BowlingGame()
        self.assertRaises(BowlingError, game.get_frame_at, 0)

    def test_game_0_frames(self):
        f = Frame(1,5)
        game = BowlingGame()
        self.assertEqual(0, game.calculate_score())

    def test_game_points_sum(self):
        game = BowlingGame()
        f0 = Frame(1, 5)
        f1 = Frame(3,6)
        f2 = Frame(7,2)
        f3 = Frame(3,6)
        f4 = Frame(4,4)
        f5 = Frame(5,3)
        f6 = Frame(3,3)
        f7 = Frame(4,5)
        f8 = Frame(8,1)
        f9 = Frame(2,6)

        game.add_frame(f0)
        game.add_frame(f1)
        game.add_frame(f2)
        game.add_frame(f3)
        game.add_frame(f4)
        game.add_frame(f5)
        game.add_frame(f6)
        game.add_frame(f7)
        game.add_frame(f8)
        game.add_frame(f9)

        self.assertEqual(81, game.calculate_score())

    def test_game_more_than_10_frames(self):
        game = BowlingGame()
        f0 = Frame(1, 5)
        f1 = Frame(3,6)
        f2 = Frame(7,2)
        f3 = Frame(3,6)
        f4 = Frame(4,4)
        f5 = Frame(5,3)
        f6 = Frame(3,3)
        f7 = Frame(4,5)
        f8 = Frame(8,1)
        f9 = Frame(2,6)
        f10 = Frame(2, 6)

        game.add_frame(f0)
        game.add_frame(f1)
        game.add_frame(f2)
        game.add_frame(f3)
        game.add_frame(f4)
        game.add_frame(f5)
        game.add_frame(f6)
        game.add_frame(f7)
        game.add_frame(f8)
        game.add_frame(f9)

        self.assertRaises(BowlingError, game.add_frame, f10)

